name: Download Dataset from Kaggle

on:
  push

jobs:
  download-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Use Git LFS to download large files
          submodules: 'recursive'
          fetch-depth: 0
          lfs: true
      - name: Install Kaggle API
        run: pip install kaggle
      - name: Download dataset from Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p data
          kaggle datasets download -d rounakbanik/the-movies-dataset -p data/
          echo "dataset_downloaded=true" >> $GITHUB_ENV
      - name: Unzip dataset
        run: unzip -qo data/*.zip -d data/
      - name: Commit and Push changes - 1
        uses: ad-m/github-push-action@v2
        with:
            repo: https://<PAT>@github.com/GuliyaSib/movie-recomendation.git
            persist-credentials: false
            fetch-depth: 0 
            branch: main
            message: 'Automated commit and push'
