name: Movie recommendation

on: [push]

jobs:
  download-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Use Git LFS to download large files
          submodules: 'recursive'
          fetch-depth: 0
          lfs: true
      - name: Install Kaggle API
        run: pip install kaggle
      - name: download source data
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p data
          kaggle datasets download -d rounakbanik/the-movies-dataset -p data/
          echo "dataset_downloaded=true" >> $GITHUB_ENV
      - name: Unzip dataset
        run: unzip -qo data/*.zip -d data/
      - name: Upload CSV files as artifact - 1
        uses: actions/upload-artifact@v3.1.2
        with:
          name: csv-files
          path: |
            data/ratings_small.csv
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r req.txt
      - name: Preprocessing
        run: |
          python preprocess.py
      - name: train_saved Artict
        uses: actions/upload-artifact@v3.1.2
        with:
          name: train_file
          path: train.csv
      - name: test_saved Artict
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test_file
          path: test.csv
      - name: index Artict
        uses: actions/upload-artifact@v3.1.2
        with:
          name: index_file
          path: index.txt

  train_model:
    runs-on: ubuntu-latest
    needs: download-dataset
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r req_train.txt

      - name: Download preprocess
        uses: actions/download-artifact@v3
        with:
          name: train_file

      - name: Download preprocess
        uses: actions/download-artifact@v3
        with:
          name: index_file

      - name: train model
        run: |
          python model.py

      - name: Upload a Build Artifact - 2
        uses: actions/upload-artifact@v3.1.2
        with:
          name: trained_model
          path: |
            model1.h5
            model2.h5

  test-model:
    runs-on: ubuntu-latest
    needs: train_model
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r req_train.txt

      - name: Download dataset
        uses: actions/download-artifact@v3
        with:
          name: test_file

      - name: Download model
        uses: actions/download-artifact@v3
        with:
          name: trained_model

      - name: test model
        run: |
          python test.py

      - name: Upload a result
        uses: actions/upload-artifact@v3.1.2
        with:
          name: result
          path: result.txt
