name: Download Dataset from Kaggle

on:
  push

jobs:
  download-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
