name: Download Dataset from Kaggle

on: [push]

jobs:
  download-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Use Git LFS to download large files
          submodules: 'recursive'
          fetch-depth: 0
          lfs: true

      - name: Install Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r req.txt

      - name: download source data
        run: |
          gdown "https://docs.google.com/uc?id=14l62l5_wJxepLQ5CHxlriQrRk-cutsSU"

      - name: Preprocessing
        run: |
          python preprocess.py
      - name: Upload a Build Artifact - 2
        uses: actions/upload-artifact@v3.1.2
        with:
          name: preprocess_file
          path: data.csv

  train_model:
    runs-on: ubuntu-latest
    needs: download-dataset
    steps:
      - uses: actions/checkout@v3
        with:
          name: preprocess_file
      - name: Install dependencies
        run: pip install -r req_train.txt

      - name: Download preprocess
        uses: actions/download-artifact@v3
        with:
          name: preprocess_file

      - name: train model
        run: |
          python model.py

      - name: Upload a Build Artifact - 2
        uses: actions/upload-artifact@v3.1.2
        with:
          name: trained_model
          path: model1
